package com.asl.utils;

public enum QueryName {
	ABSTRACT, NEW_CLIENT, NEW_QUEUE, DELETE_QUEUE, LIST_QUEUE, POST,
	BROADCAST, READ, LIST_QUEUE_WITH_MESSAGE, CHECK_MESSAGE_FROM,
	RETRIEVE_MESSAGE, MGMT_FETCH_QUEUES, MGMT_FETCH_MESSAGES, MGMT_FETCH_MESSAGE_DETAILS,
	ONE_WAY;
}